### ISSUE TITLE
Methods missing

### ISSUE THREAD

**Issue by paztek** [Ubudu/Android-SDK#1]
The methods:

```
com.ubudu.sdk.UbuduGeofenceManager#setGeofenceDelegate
com.ubudu.sdk.UbuduBeaconManager#setBeaconDelegate
```

are not present on the interfaces, but they exist on the implementation classes: `com.ubudu.sdk.implementation.UbuduGeofenceManager` and `com.ubudu.sdk.implementation.UbuduBeaconManager`.

The README should probably be updated or even better, the `setXXXDelegate` methods moved up to the interfaces.

I just download 1.4.9 btw.

Regards,

**Comment by zioolek** [comment]
Please try:
`com.ubudu.sdk.UbuduAreaManager.setAreaDelegate`

We will update docs soon.
