### ISSUE TITLE
UbuduSDK eclipse

### ISSUE THREAD

**Issue by lion1874** [Ubudu/Android-SDK#4]
I tested both of the SDK, android studio version works fine and smooth, but something went wrong when i launched the eclipse demo app, here it's some of the log.

Rejecting re-init on previously-failed class java.lang.Class<com.ubudu.sdk.implementation.UbuduGeofenceManager>

java.lang.NoClassDefFoundError: com.ubudu.sdk.implementation.UbuduGeofenceManager

**Comment by MGasztold** [comment]
Hello, thank you for feedback . We actually work only in Android Studio these days so Eclipse demo app might be a bit outdated. I will have a look at it and get back to you.

**Comment by MGasztold** [comment]
@lion1874  Please check out the Eclipse demo app now. You should just import the `google-play-services_lib` project and `UbuduSDKDemo` project to an empty workspace. Let me know if it works for you. Thanks.

**Comment by lion1874** [comment]
I just have a test on the Eclipse demo, everything is work fine now, thank you for the fast reply.
