### ISSUE TITLE
Cannot evaluate UbuduBeaconRegion.toString() at "areaEntered" method

### ISSUE THREAD

**Issue by PimientosVerdesFritos** [Ubudu/Android-SDK#5]
Hi, I just run UbuduSDKDemo, after setting up every beacon in the web platform and im getting this error just when my app launch triggers areaEntered(UbuduArea area) method, its the parameter "area" wich is bringing the exception:

"Method threw 'java.lang.NullPointerException' exception. Cannot evaluate com.ubudu.sdk.implementation.UbuduBeaconRegion.toString()"

Any Ideas?

**Comment by MGasztold** [comment]
Hello,

Thank you for reporting this issue. It looks like you have found a bug.
Is it possible for you to send me the full crash trace?

Besides that I will investigate this on my own. 

I hope to release a fixed version for you by tomorrow.

**Comment by MGasztold** [comment]
Please try using:

`compile('com.ubudu.sdk:ubudu-sdk:2.2.8-SNAPSHOT@aar') {
        transitive = true
    }`

and tell me if the crash still occurs in your application. Thanks.

**Comment by PimientosVerdesFritos** [comment]
Ok that solved it, thank you very much!

**Comment by MGasztold** [comment]
Ok great. I will push an official 2.2.8 release to this repository by the end of the day.

**Comment by MGasztold** [comment]
Official release v2.2.8 is online.
